### PR TITLE
wouldn't if(!myName) cover myName === null.

### PR DESCRIPTION
**Pull request by siraj-samsudeen**
I tested it in Google Chrome with only the first part of "if(!myName || myName === null)" and it works when I cancel the prompt and when I press Ok without entering anything.

### CODE REVIEW

**Comment by chrisdavidmills** [comment]
Yeah, I think you're right here — I can't remember why I wrote it like this ;-)

**Comment by chrisdavidmills** [comment]
Thanks for the contribution.

**Comment by siraj-samsudeen** [comment]
Thanks a lot Chris. I am new to JS and to MDN. I loved the Django tutorial on MDN and hence decided to do everything in MDN from scratch. I am so glad to make my first contribution with my little knowledge of JS.

**Comment by chrisdavidmills** [comment]
>  I am so glad to make my first contribution with my little knowledge of JS.

That's great, I am so pleased for you. 

I am glad you enjoyed the Django tutorial too!

**Pull request merged**
