### PR TITLE
Replaced innerHTML with innerText in scripts/main.js

### PR DESCRIPTION
**Pull request by FatihTheDev**

### CODE REVIEW

**Comment by pepelsbey** [comment]
Hey! Thank you for the suggestion. This demo is used in the [JavaScript basics](https://developer.mozilla.org/en-US/docs/Learn/Getting_started_with_the_web/JavaScript_basics) article that has already used `textContent` in the examples. I’d say it would be good to align the demo with the article.

By the way, there’s another `innerHTML` instance earlier in the script that would be good to replace, too.

As for the comment about using `innerHTML`, I think it belongs in the article, not the demo. However, since the article is for beginners, I’d leave it as simple as possible and suggest the safer option by default.

**Comment by FatihTheDev** [comment]
> By the way, there’s another `innerHTML` instance earlier in the script that would be good to replace, too.

I just realized that after pushing the changes. 😅

Thank you for the response!

**Comment by pepelsbey** [comment]
@FatihTheDev hey! Do you think we can finish this one? If you have time, of course. Otherwise, I’d close the PR.

**Comment by pepelsbey** [comment]
Closing for now. Let me know if you’d like to get back to it.

**Pull request closed without merging**
